# Generated by Django 5.1.2 on 2025-07-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homecontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('mail', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
