# Generated by Django 5.1.2 on 2025-10-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0002_homecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=500, null=True, upload_to='photo/')),
            ],
        ),
    ]
