# Generated by Django 5.1.2 on 2025-10-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0003_admin_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_home2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(default=None, max_length=500, null=True, upload_to='photo/')),
                ('link', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
