# Generated by Django 5.1.2 on 2025-10-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0005_admin_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('album_art', models.ImageField(blank=True, null=True, upload_to='album_art/')),
            ],
        ),
    ]
